version: '2.1'

services:
  mysql:
    image: 'docker.io/bitnami/mysql:8.0-debian-10'
    ports:
      - '33061:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=library
      - MYSQL_PASSWORD=library
      - MYSQL_DATABASE=library_spring
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql_data:
    driver: local