spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:33061/library_spring
    username: library
    password: "library"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

logging:
  file:
    name: D:\java\learn\book_library_spring\logs\
  pattern:
    file: "%d{HH:mm:ss} %-5p [%c] - %m%n"

  level:
    ROOT: error
    org.springframework: trace
    javax.faces: trace
    org.comnifaces: trace
    org.springframework.security: trace
    org.hibernate: trace
    org.hibernate.type.descriptor: trace