spring:
  datasource:
    default-catalog: library
    jndi-name: jdbc/Library
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: orh.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

logging:
  file:
    name: D:\java\learn\book_library_spring\logs\logs.log
  pattern:
    file: "%d{HH:mm:ss} %-5p [%c] - %m%n"

  level:
    ROOT: error
    org.springframework: trace
    javax.faces: trace
    org.comnifaces: trace
    org.springframework.security: trace
    org.hibernate: trace
    org.hibernate.type.descriptor: trace